### ISSUE TITLE
Resolve note on Windows build

### ISSUE THREAD

**Issue by geanders** [geanders/weathermetrics#20]
```
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Brooke Anderson <brooke.anderson@colostate.edu>'

Version contains large components (1.2.1.9000)

License components with restrictions and base license permitting such:
  MIT + file LICENSE
File 'LICENSE':
  YEAR: 2015
  COPYRIGHT HOLDER: G. Brooke Anderson

The Date field is over a month old.
```

I'm not sure if this is the date or the size. I'm not sure what would make this large. How big are the new example data files?

**Comment by jferreri** [comment]
I think I added 6 new data sets, all of which have only 7 rows and 3 variables at most. they saved as .rda so I am not sure if .RData does something to condense these? I was searching around for a function to check the size of an object in R, but so far have not been able to find the correct one. I will keep searching.

**Comment by geanders** [comment]
No, I'm getting this with another package I have. I think it might just be a thing with the Windows R development version, now that I've nosed around a bit more. So not something we need to fix.
