### ISSUE TITLE
Wrap the arguments `round.out` and `round` into a single argument, `round`

### ISSUE THREAD

**Issue by geanders** [geanders/weathermetrics#25]
You can do everything you want for rounding using just the argument `round`. Let the convention be that the selection `round = NULL` means no rounding. Within the function, first use:

```
if(is.null(round)){
    round.out <- FALSE
}
```

and then you should be able to proceed as before. This will limit the number of arguments that the user needs to understand and use.

**Comment by jferreri** [comment]
I ended up changing this a little differently. Since NOAA's converter rounds 1 decimal place, I set the default for round within the function to be 1 when `round = TRUE`. Then, when `round =  FALSE` the value would not be rounded. Is this okay?

**Comment by geanders** [comment]
No, I think there could be people who would rather round to different values.... Give the other a try, and if you have problems I'll help you out.

**Comment by geanders** [comment]
Done.
